server:
  port: 8888  # ??? ?? ?? ?? ??

 # db config
spring:
  datasource:  #spring.datasource
    driver-class-name: org.mariadb.jdbc.Driver  # mariadb
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

  jpa:   # spring.jpa
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true